# 
from __future__ import annotations
from enum import StrEnum

class BoardBlock(StrEnum):
    """Available Board Blocks."""
    REGISTERS_BLOCK_1 = "registers_block_1"
    REGISTERS_BLOCK_2 = "registers_block_2"

class RegisterAreaName(StrEnum):
    """Available Register Areas."""
    AREA_A = "area_a"
    AREA_B = "area_b"
    AREA_C = "area_c"
    AREA_D = "area_d"

class Board(StrEnum):
    """Available Boards."""
    XY_MOD01_SHT20 = "xy_mod01_sht20"
    GL_TH02_PE = "gl_th02_pe"
    EASTRON_SDM120M = "eastron_sdm120m"
    ELETECHSUP_NT18B07 = "eletechsup_nt18b07"
    ELETECHSUP_N4DBA06 = "eletechsup_n4dba06"
    ELETECHSUP_N4ROD08 = "eletechsup_n4rod08"
    ELETECHSUP_R4D3B16 = "eletechsup_r4d3b16"
    ELETECHSUP_10IOA04 = "eletechsup_10ioa04"
    ENEREN_RER020I_EFHR0_EVO = "eneren_rer_020i"
    AERMEC_HMI080 = "aermec_hmi080"
    WAVESHARE_RTU_RELAY = "waveshare_rtu_relay"
    
# class NumberMode(StrEnum):
#     """Available Number Modes."""
#     BOX = "box"
#     SLIDER = "slider"
#     AUTO = "auto"

class SwitchFunction(StrEnum):
    """Available Switch Channels."""
    CHANNEL_00 = "channel_00"
    CHANNEL_01 = "channel_01"
    CHANNEL_02 = "channel_02"
    CHANNEL_03 = "channel_03"
    CHANNEL_04 = "channel_04"
    CHANNEL_05 = "channel_05"
    CHANNEL_06 = "channel_06"
    CHANNEL_07 = "channel_07"
    CHANNEL_08 = "channel_08"
    CHANNEL_09 = "channel_09"
    CHANNEL_10 = "channel_10"
    CHANNEL_11 = "channel_11"
    CHANNEL_12 = "channel_12"
    CHANNEL_13 = "channel_13"
    CHANNEL_14 = "channel_14"
    CHANNEL_15 = "channel_15"
    CHANNEL_16 = "channel_16"
    CHANNEL_17 = "channel_17"
    CHANNEL_18 = "channel_18"
    CHANNEL_19 = "channel_19"
    CHANNEL_20 = "channel_20"
    CHANNEL_21 = "channel_21"
    CHANNEL_22 = "channel_22"
    CHANNEL_23 = "channel_23"
    CHANNEL_24 = "channel_24"
    CHANNEL_25 = "channel_25"
    CHANNEL_26 = "channel_26"
    CHANNEL_27 = "channel_27"
    CHANNEL_28 = "channel_28"
    CHANNEL_29 = "channel_29"
    CHANNEL_30 = "channel_30"
    CHANNEL_31 = "channel_31"
    CHANNEL_32 = "channel_32"

class NumberFunction(StrEnum):
    VOLTAGE_OUT2 = "voltage_out2"
    VOLTAGE_OUT2_PERCENTAGE = "voltage_out2_percentage"
    
class SensorFunction(StrEnum):
    TEMPERATURE = "temperature"
    HUMIDITY = "humidity"

    VOLTAGE = "voltage"
    CURRENT = "current"
    ACTIVE_POWER = "active_power"
    TOTAL_ACTIVE_ENERGY = "total_active_energy"

    VOLTAGE_IN2 = "voltage_in2"
    VOLTAGE_IN2_PERCENTAGE = "voltage_in2_percentage"

    CHANNEL_00 = "channel_00"
    CHANNEL_01 = "channel_01"
    CHANNEL_02 = "channel_02"
    CHANNEL_03 = "channel_03"
    CHANNEL_04 = "channel_04"
    CHANNEL_05 = "channel_05"
    CHANNEL_06 = "channel_06"
    CHANNEL_07 = "channel_07"
    CHANNEL_08 = "channel_08"
    CHANNEL_09 = "channel_09"
    CHANNEL_10 = "channel_10"
    CHANNEL_11 = "channel_11"
    CHANNEL_12 = "channel_12"
    CHANNEL_13 = "channel_13"
    CHANNEL_14 = "channel_14"

class AermecHMI080BinarySensorFunction(StrEnum):
    """..."""
    HEAT_2_WAY_VALVE = "ro_heat_2_way_valve"
    COM_ERROR_BETWEEN_THE_WIRED_CTRL_AND_IDU = "ro_communication_error_between_the_wired_controller_and_idu"
    COM_ERROR_BETWEEN_THE_WIRED_CTRL_AND_ODU = "ro_communication_error_between_the_wired_controller_and_odu"
    COM_ERROR_BETWEEN_THE_WIRED_CTRL_AND_DRIVE = "ro_communication_error_between_the_wired_controller_and_drive"
    HP_ANTIFREE = "ro_hp_antifree"
    COMPRESSOR_STATE = "ro_compressor_state"
    ODU_FAN_STATE = "ro_odu_fan_state"
    FOUR_WAY_VALVE_STATE = "ro_4_way_valve_state"
    COMPRESSOR_CRANKCASE_HEATER_STATE = "ro_compressor_crankcase_heater_state"
    UNDERPAN_HEATER_STATE = "ro_underpan_heater_state"
    DEFROSTING_STATE = "ro_defrosting_state"
    OIL_RETURN_STATE = "ro_oil_return_state"
    AMBIENT_TEMP_SENSOR_ERROR = "ro_ambient_temp_sensor_error"
    DEFROST_TEMP_SENSOR_ERROR = "ro_defrost_temp_sensor_error"
    DISCHARGE_TEMP_SENSOR_ERROR = "ro_discharge_temp_sensor_error"
    SUCTION_TEMP_SENSOR_ERROR = "ro_suction_temp_sensor_error"
    ODU_FAN_ERROR = "ro_odu_fan_error"
    HIGH_PRESSURE_SENSOR_ERROR = "ro_high_pressure_sensor_error"
    HIGH_PRESSURE_PROTECTION = "ro_high_pressure_protection"
    LOW_PRESSURE_PROTECTION = "ro_low_pressure_protection"
    HIGH_DISCHARGE_PROTECTION = "ro_high_discharge_protection"
    CAPACITY_DIP_SETTING_ERROR = "ro_capacity_dip_setting_error"
    COMMUNICATION_ERROR_BETWEEN_IDU_AND_ODU = "ro_communication_error_between_idu_and_odu"
    ECONOMIZER_IN_SENSOR_ERROR = "ro_economizer_in_sensor_error"
    ECONOMIZER_OUT_SENSOR_ERROR = "ro_economizer_out_sensor_error"
    SYSTEM_RECOVERABLE_PROTECTION = "ro_system_recoverable_protection"
    SYSTEM_IRRECOVERABLE_PROTECTION = "ro_system_irrecoverable_protection"
    FLOW_SWITCH_PROTECTION = "ro_flow_switch_protection"
    DC_BUS_LOW_VOLTAGE_OR_VOLTAGE_DROP = "ro_dc_bus_low_voltage_or_voltage_drop"
    DC_BUS_OVER_VOLTAGE = "ro_dc_bus_over_voltage"
    AC_CURRENT_PROTECTION_INPUT_SIDE = "ro_ac_current_protection_input_side"
    IPM_ERROR = "ro_ipm_error"
    PFC_ERROR = "ro_pfc_error"
    STARTUP_ERROR = "ro_startup_error"
    PHASE_LOSS = "ro_phase_loss"
    DRIVE_MODULE_RESETTING = "ro_drive_module_resetting"
    COMPRESSOR_OVERCURRENT = "ro_compressor_overcurrent"
    OVER_SPEED = "ro_over_speed"
    CHARGING_CIRCUIT_ERROR_OR_CURRENT_SENSOR_ERROR = "ro_charging_circuit_error_or_current_sensor_error"
    DESYNCHRONIZING = "ro_desynchronizing"
    COMPRESSOR_STALLING = "ro_compressor_stalling"
    DRIVE_COMMUNICATION_ERROR = "ro_drive_communication_error"
    RADIATOR_OR_IPM_OR_PFC_OVER_TEMPERATURE = "ro_radiator_or_ipm_or_pfc_over_temperature"
    DEFECTIVE_RADIATOR_OR_IPM_OR_PFC = "ro_defective_radiator_or_ipm_or_pfc"
    CHARGING_CIRCUIT_ERROR = "ro_charging_circuit_error"
    AC_INPUT_VOLTAGE_ERROR = "ro_ac_input_voltage_error"
    DRIVE_BOARD_TEMP_SENSOR_ERROR = "ro_drive_board_temp_sensor_error"
    AC_CONTACTOR_PROTECTION_OR_INPUT_CROSS_ZERO_ERROR = "ro_ac_contactor_protection_or_input_cross_zero_error"
    TEMP_DRIFT_PROTECTION = "ro_temp_drift_protection"
    SENSOR_CONNECTION_PROTECTION_CONNN= "ro_sensor_connection_protection_connection_to_phase_u_or_v_failed"
    CONDENSER_LEAVING_WATER_TEMP_SENSOR_ERROR = "ro_condenser_leaving_water_temp_sensor_error"
    E_HEATER_LEAVING_WATER_TEMP_SENSOR_ERROR = "ro_e_heater_leaving_water_temp_sensor_error"
    REFRIGERANT_LIQUID_TEMP_SENSOR_ERROR = "ro_refrigerant_liquid_temp_sensor_error"
    CONDENSER_ENTERING_WATER_TEMP_SENSOR_ERROR = "ro_condenser_entering_water_temp_sensor_error"
    WATER_TANK_TEMP_SENSOR_ERROR = "ro_water_tank_temp_sensor_error"
    REFRIGERANT_VAPOR_LINE_TEMP_SENSOR_ERROR = "ro_refrigerant_vapor_line_temp_sensor_error"
    REMOTE_ROOM_TEMP_SENSOR_ERROR = "ro_remote_room_temp_sensor_error"
    OTHER_HEAT_SOURCE_STATE = "ro_other_heat_source_state"
    FLOW_SWITCH_STATE = "ro_flow_switch_state"
    IDU_E_HEATER_1_STATE = "ro_idu_e_heater_1_state"
    IDU_E_HEATER_2_STATE = "ro_idu_e_heater_2_state"
    WATER_TANK_HEATER_STATE = "ro_water_tank_heater_state"
    IDU_WATER_PUMP_STATE = "ro_idu_water_pump_state"
    CIRCULATING_2_WAY_VALVE_STATE = "ro_circulating_2_way_valve_state"
    PLATE_HEATER_STATE = "ro_plate_heater_state"
    THREE_WAY_VALVE_STATE = "ro_3_way_valve_state"
    GATE_CTRL = "ro_gate_ctrl"
    JUMPER_CAP_ERROR = "ro_jumper_cap_error"
    E_HEATER_1_WELDING_PROTECTION = "ro_e_heater_1_welding_protection"
    E_HEATER_2_WELDING_PROTECTION = "ro_e_heater_2_welding_protection"
    WATER_HEATER_WELDING_PROTECTION = "ro_water_heater_welding_protection"
    WATER_FLOW_PROTECTION = "ro_water_flow_protection"
    IDU_RECOVERABLE_PROTECTION = "ro_idu_recoverable_protection"
    IDU_IRRECOVERABLE_PROTECTION = "ro_idu_irrecoverable_protection"


class AermecHMI080SensorFunction(StrEnum):
    """..."""
    UNIT_STATUS = "ro_unit_status"
    T_OUTDOOR = "ro_t_outdoor"
    T_DISCHARGE = "ro_t_discharge"
    T_DEFROST = "ro_t_defrost"
    T_SUCTION = "ro_t_suction"
    T_ECONOMIZER_IN = "ro_t_economizer_in"
    T_ECONOMIZER_OUT = "ro_t_economizer_out"
    DIS_PRESSURE = "ro_dis_pressure"
    T_WATER_OUT_PE = "ro_t_water_out_pe"
    T_OPTIONAL_WATER_SENS = "ro_t_optional_water_sen"
    T_WATER_IN_PE = "ro_t_water_in_pe"
    T_TANK_CTRL = "ro_t_tank_ctrl"
    T_REMOTE_ROOM = "ro_t_remote_room"
    T_GAS_PIPE = "ro_t_gas_pipe"
    T_LIQUID_PIPE = "ro_t_liquid_pipe"
    THERMOSTAT = "ro_thermostat"
    T_FLOOR_DEBUG = "ro_t_floor_debug"
    DEBUG_TIME = "ro_debug_time"
    DISINFECTION = "ro_disinfection"
    ERROR_TIME_FOR_FLOOR_DEBUG = "ro_error_time_for_floor_debug"
    T_WEATHER_DEPEND = "ro_t_weather_depend"

class AermecHMI080SwitchFunction(StrEnum):
    """..."""
    DEVICE_POWER_CONTROL = "rw_device_power_control"
    WEEKLY_TIMER = "rw_weekly_timer"
    CLOCK_TIMER = "rw_clock_timer"
    TEMP_TIMER = "rw_temp_timer"
    GATE_CTRL = "rw_gate_ctrl"
    SOLAR_HEATER = "rw_solar_heater"
    CTRL_STATE = "rw_ctrl_state"
    FAST_HOT_WATER = "rw_fast_hot_water"
    COOL_AND_HOT_WATER_PRIORITY = "rw_cool_and_hot_water_priority"
    HEAT_AND_HOT_WATER_PRIORITY = "rw_heat_and_hot_water_priority"
    QUIET_MODE = "rw_quiet_mode"
    WEATHER_DEPEND = "rw_weather_depend"
    DISINFECTION = "rw_disinfection"
    FLOOR_DEBUG = "rw_floor_debug"
    FLOOR_DEBUG_START_STOP = "rw_floor_debug_start_stop"
    EMERGENCE_MODE = "rw_emergence_mode"
    OTHER_THERMAL = "rw_other_thermal"
    WATER_TANK = "rw_water_tank"
    SOLAR_SETTING = "rw_solar_setting"
    REMOTE_SENSOR = "rw_remote_sensor"
    HOLIDAY_MODE = "rw_holiday_mode"
    REFRI_RECOVERY = "rw_refri_recovery"
    MANUAL_DEFROST = "rw_manual_defrost"
    COOL_2_WAY_VALVE = "rw_cool_2_way_valve"

class AermecHMI080NumberFunction(StrEnum):
    """..."""

    MODE = "rw_mode"
    OPTIONAL_E_HEATER = "rw_optional_e_heater"
    DISINFECTION_TEMP = "rw_disinfection_temp"
    FLOR_DEBUG_SEGMENTS = "rw_floor_debug_segments"
    FLOR_DEBUG_PERIOD_1_TEMP = "rw_floor_debug_period_1_temp"
    DELTA_T_OF_SEGMENT = "rw_delta_t_of_segment"
    SEGMENT_TIME = "rw_segment_time"
    WOT_COOL = "rw_wot_cool"
    WOT_HEAT = "rw_wot_heat"
    RT_COOL = "rw_rt_cool"
    RT_HEAT = "rw_rt_heat"
    T_WATER_TANK = "rw_t_water_tank"
    T_EHEATER = "rw_t_eheater"
    T_OTHER_SWITCH_ON = "rw_t_other_switch_on"
    T_HP_MAX = "rw_t_hp_max"
    UPPER_AT_HEAT = "rw_upper_at_heat"
    LOWER_AT_HEAT = "rw_lower_at_heat"
    UPPER_RT_HEAT = "rw_upper_rt_heat"
    LOWER_RT_HEAT = "rw_lower_rt_heat"
    UPPER_WT_HEAT = "rw_upper_wt_heat"
    LOWER_WT_HEAT = "rw_lower_wt_heat"
    UPPER_AT_COOL = "rw_upper_at_cool"
    LOWER_AT_COOL = "rw_lower_at_cool"
    UPPER_RT_COOL = "rw_upper_rt_cool"
    LOWER_RT_COOL = "rw_lower_rt_cool"
    UPPER_WT_COOL = "rw_upper_wt_cool"
    LOWER_WT_COOL = "rw_lower_wt_cool"
    DELTA_T_COOL = "rw_delta_t_cool"
    DELTA_T_HEAT = "rw_delta_t_heat"
    DELTA_T_HOT_WATER = "rw_delta_t_hot_water"
    DELTA_T_ROOM_TEMP = "rw_delta_t_room_temp"
    COOL_RUN_TIME = "rw_cool_run_time"
    HEAT_RUN_TIME = "rw_heat_run_time"
    OTHER_THERMAL_LOGIC = "rw_other_thermal_logic"
    TANK_HEATER = "rw_tank_heater"
    OPTIONAL_E_HEATER_LOGIC = "rw_optional_e_heater_logic"
    CURRENT_LIMIT_VALUE = "rw_current_limit_value"
    RW_THERMOSTAT = "rw_thermostat"
    FORCE_MODE = "rw_force_mode"
    AIR_REMOVAL = "rw_air_removal"

class EnerenRER020IBinarySensorFunction(StrEnum):
    """..."""

    PRESENZA_ALLARME = "ro_presenza_allarme"
    PRESENZA_AVVERTIMENTO = "ro_presenza_avvertimento"
    FILTRI_DA_PULIRE = "ro_filtri_da_pulire"
    MANCANZA_COMUNICAZIONE_CON_DISPLAY = "ro_mancanza_comunicazione_con_display"
    PRESENZA_OPZIONE_SERRANDE_ESTERNE = "ro_presenza_opzione_serrande_esterne"
    PRESENZA_OPZIONE_SBRINAMENTO_RECUPERATORE = "ro_presenza_opzione_sbrinamento_recuperatore"
    PRESENZA_FREE_COOLING = "ro_presenza_free_cooling"
    ALLARME_SONDA = "ro_allarme_sonda"
    ALLARME_SONDA_CO2_AMBIENTE = "ro_allarme_sonda_co2_ambiente"
    ALLARME_ALTA_PRESSIONE = "ro_allarme_alta_pressione"
    AVVERTIMENTO_BASSA_TEMPERATURA_ACQUA_PER_ON_COMPRESSORE = "ro_avvertimento_bassa_temperatura_acqua_per_on_compressore"
    AVVERTIMENTO_ALTA_TEMPERATURA_ACQUA_PER_ON_COMPRESSORE = "ro_avvertimento_alta_temperatura_acqua_per_on_compressore"
    AVVERTIMENTO_RISCHIO_CONGELAMENTO_BATTERIA_ACQUA = "ro_avvertimento_rischio_congelamento_batteria_acqua"
    ALLARME_DEW_POINT = "ro_allarme_dew_point"
    STATO_COMPRESSORE = "ro_stato_compressore"
    STATO_FREE_COOLING = "ro_stato_free_cooling"
    RICHIESTA_ACQUA_DA_IMPIANTO = "ro_richiesta_acqua_da_impianto"
    RICHIESTA_DEUMIDIFICA = "ro_richiesta_deumidifica"
    RICHIESTA_RAFFREDDAMENTO = "ro_richiesta_raffreddamento"
    RICHIESTA_RISCALDAMENTO = "ro_richiesta_riscaldamento"
    PRESENZA_SONDA_T_MANDATA_ARIA = "ro_presenza_sonda_t_mandata_aria"
    CONTROLLO_TEMPERATURA_MANDATA_ONOFF_ATTIVO = "ro_controllo_temperatura_di_mandata_onoff_attivo"
    PRESENZA_FUNZIONE_CONTROLLO_TEMPERATURA_DI_MANDATA_MODULANTE = "ro_presenza_funzione_controllo_di_temperatura_di_mandata_modulante"

class EnerenRER020ISensorFunction(StrEnum):
    """..."""
    
    TEMPERATURA_AMBIENTE = "ro_temperatura_ambiente"
    UMIDITA_RELATIVA_AMBIENTE = "ro_umidita_relativa_ambiente"
    SONDA_CO2 = "ro_sonda_co2"
    TEMPERATURA_ACQUA = "ro_temperatura_acqua"
    TEMPERATURA_ESTERNA = "ro_temperatura_esterna"
    STATO_VENTILATORE_MANDATA = "ro_stato_ventilatore_mandata"
    STATO_VENTILATORE_ESTRAZIONE = "ro_stato_ventilatore_estrazione"
    SET_TEMPERATURE_EFFETTIVO = "ro_set_temperatura_effettivo"
    SET_UMIDITA_EFFETTIVO = "ro_set_umidita_effettivo"
    SET_RICAMBIO_EFFETTIVO = "ro_set_ricambio_effettivo"
    ORE_FUNZIONAMENTO_UNITA = "ro_ore_funzionamento_unita"
    RELEASE_SOFTWARE_SCHEDA = "ro_release_software_scheda"
    TEMPERATURA_MANDATA_ARIA = "ro_temperatura_mandata_aria"

class EnerenRER020ISwitchFunction(StrEnum):
    """..."""

    DEVICE_POWER_CONTROL = "rw_device_power_control"
    STAGIONE = "rw_stagione"
    FORZATURA_OFF_TRATTAMENTO = "rw_forzatura_off_trattamento"
    RESET_ALLARMI= "rw_reset_allarmi"
    RESET_PULIZIA_FILTRI = "rw_reset_pulizia_filtri"
    ABILITAZIONE_FORZATURA_FREE_COOLING = "rw_abilitazione_forzatura_free_cooling"
    FORZATURA_FREE_COOLING = "rw_forzatura_free_cooling"
    FORZATURA_RISCALDAMENTO = "rw_forzatura_riscaldamento"
    FORZATURA_RAFFREDDAMENTO = "rw_forzatura_raffreddamento"
    ABILITAZIONE_FORZATURA_DEUMIDIFICA_UMIDIFICA = "rw_abilitazione_forzatura_deumidifica_umidifica"
    FORZATURA_DEUMIDIFICA = "rw_forzatura_deumidifica"
    RICHIESTA_VENTILAZIONE_DI_RICIRCOLO = "rw_richiesta_ventilazione_di_ricircolo"
    UNITA_MISURA_TEMPERATURA = "rw_unita_di_misura_temperatura"
    GESTIONE_CONTROLLO_TEMPERATURA_MANDATA = "rw_gestione_controllo_temperatura_mandata"
    GESTIONE_CONTROLLO_DEW_POINT = "rw_gestione_controllo_dew_point"

class EnerenRER020INumberFunction(StrEnum):
    """..."""

    SET_TEMPERATURE_AMBIENTE_IN_CENSIUS = "rw_set_temperatura_ambiente_in_celsius"
    SET_UMIDITA_RELATIVA_AMBIENTE = "rw_set_umidita_relativa_ambiente"
    SET_RICAMBIO = "rw_set_ricambio"
    OROLOGIO_ORE = "rw_orologio_ore"
    OROLOGIO_MINUTI = "rw_orologio_minuti"
    OROLOGIO_GIORNO = "rw_orologio_giorno"
    OROLOGIO_MESE = "rw_orologio_mese"
    OROLOGIO_ANNO = "rw_orologio_anno"
    OROLOGIO_GIORNO_DELLA_SETTIMANA = "rw_orologio_giorno_della_settimana"
    FORZATURA_VALVOLA_ACQUA_MODULANTE = "rw_forzatura_valvola_acqua_modulante"
    TEMPERATURA_MINIMA_INVERNALE_SENZA_RISCALDAMENTO = "rw_temperatura_minima_invernale_senza_riscaldamento"
    TEMPERATURA_MASSIMA_ESTIVA_SENZA_RAFFREDDAMENTO = "rw_temperatura_massima_estiva_senza_raffreddamento"
    GESTIONE_RAFFREDDAMENTO = "rw_gestione_raffreddamento"
    PROTEZIONE_DEW_POINT_DIFFERENZIALE = "rw_protezione_dew_point_differenziale"
    PROTEZIONE_DEW_POINT_VALORE_T_DEW_POINT = "rw_protezione_dew_point_valore_t_dew_point"
    ORE_ATTESA_PROMEMORIA_PULIZIA_FILTRI_SPORCHI = "rw_ore_di_attesa_promemoria_pulizia_filtri_sporchi"
    RICHIESTA_ATTIVAZIONE_COMPRESSORE = "rw_richiesta_attivazione_compressore"

